### PR TITLE
Make result field values accessible by name on `BinaryDataPacket`s, too

### PR DESCRIPTION
**Pull request by KOGI**
This makes accessing results of prepared statements consistent with accessing results of non-prepared statements.

### CODE REVIEW

**Comment by KOGI** [comment]
It might be best to review each of these commits individually. The first is just refactoring existing functionality up to the parent class. The second commit is where the actual usefulness of this PR appears.

**Comment by KOGI** [comment]
@adamlofts it looks like the dartanalyzer check is failing on a couple issues that aren't related to the code I changed. It appears that it may have something to do with the differences between Dart 2.1.0 and Dart 2.2.0

**Comment by adamlofts** [comment]
Don't worry about the analyser warning.

I am a bit dubious overloading the [] operator with int and string values since I think the dart expectation is that [] always takes a int.

How about we instead add an `Row.asMap()` function which will return a Map<String, Object>.

**Comment by adamlofts** [comment]
I see that dart List already has an asMap function and that your commit just makes things consistent so I am going to merge. In future I would like to change the api, which I will log in a new bug.

**Pull request merged**
