### PR TITLE
Added caching_sha2_password support for mysql1

### PR DESCRIPTION
**Pull request by Zaryob**
This just needs some additions into auth handler.
* getHash: function modified to convert both native password and sha2 based password.
* Plugin name statics moved to handlers/handler.dart to beware using it recursively.
* Added a parameter for AuthHandler named `plugin`

### CODE REVIEW

**Comment by adamlofts** [comment]
Hi! Thanks for the contribution.

Can you update the PR so one of the tests uses this authentication in the CI?

**Comment by Zaryob** [comment]
> Hi! Thanks for the contribution.
> 
> Can you update the PR so one of the tests uses this authentication in the CI?

I dont know how to do that

**Comment by Zaryob** [comment]
I reverted tests but something happened. It says not datas overlap.

**Comment by adamlofts** [comment]
This new functionality needs to be tested in the CI so we can be confident that it is working properly and that it will not break in future. Its fine to make changes to the test files.

If you don't know how to do it I may get around to it at some point.

**Comment by Zaryob** [comment]
> This new functionality needs to be tested in the CI so we can be confident that it is working properly and that it will not break in future. Its fine to make changes to the test files.
> 
> If you don't know how to do it I may get around to it at some point.

I dont know actually. You may deal with it. I just changed this things to use it in my application. Just want to push as PR to make help whoever lives that problem.

**Pull request closed without merging**
